POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRhcHNhIiwiaWQiOiI2NjE2ODJhOTEwZGI1ZWMzYjZlNmI1ZmYiLCJpYXQiOjE3MTI3NTEzMTV9.YkSBOctgUjpHAfNz-tma2PnEg0GkrXMQaGOSdZjpotI

{
  "title": "XY",
  "author": "authooorrr",
  "url": "nfnfnnfnfnfn",
  "likes": 8,
  "userId": "661682a910db5ec3b6e6b5ff"
}